<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateProgramFile>false</GenerateProgramFile>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateTestingPlatformEntryPoint>false</GenerateTestingPlatformEntryPoint>
  </PropertyGroup>

  <!-- <ItemGroup>
    <ProjectReference Include="../../realsharpino/Sharpino/Sharpino.Lib/Sharpino.Lib.fsproj" />
  </ItemGroup> -->

  <ItemGroup>
    <ProjectReference Include="../blazorBookLibrary.Shared/blazorBookLibrary.Shared.fsproj" />
    <ProjectReference Include="../blazorBookLibrary.Data/blazorBookLibrary.Data.csproj" />
  </ItemGroup>
  <ItemGroup> 
    <None Include="Templates/en/ReservationNotification.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/it/ReservationNotification.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/en/ReservationNotificationSubject.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/it/ReservationNotificationSubject.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/en/LoanNotification.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/it/LoanNotification.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/en/LoanNotificationSubject.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/it/LoanNotificationSubject.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/en/LoanReturnNotification.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/it/LoanReturnNotification.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/en/LoanReturnNotificationSubject.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/it/LoanReturnNotificationSubject.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/en/agreement.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/it/agreement.txt" CopyToOutputDirectory="PreserveNewest" />

    <None Include="Templates/en/PatronInvitationBody.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/it/PatronInvitationBody.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/en/PatronInvitationSubject.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Templates/it/PatronInvitationSubject.txt" CopyToOutputDirectory="PreserveNewest" />

    <None Include="InAppTemplates/en/ReservationNotification.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="InAppTemplates/it/ReservationNotification.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="InAppTemplates/en/LoanNotification.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="InAppTemplates/it/LoanNotification.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="InAppTemplates/en/LoanReturnNotification.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="InAppTemplates/it/LoanReturnNotification.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="InAppTemplates/en/PatronInvitationBody.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="InAppTemplates/it/PatronInvitationBody.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Slices/Book/Events.fs" />
    <Compile Include="Slices/Book/Commands.fs" />
    <Compile Include="Slices/Author/Events.fs" />
    <Compile Include="Slices/Author/Commands.fs" />
    <Compile Include="Slices/Editor/Events.fs" />
    <Compile Include="Slices/Editor/Commands.fs" />
    <Compile Include="Slices/Reservation/Events.fs" />
    <Compile Include="Slices/Reservation/Commands.fs" />
    <Compile Include="Slices/Loan/Events.fs" />
    <Compile Include="Slices/Loan/Commands.fs" />
    <Compile Include="Slices/User/Events.fs" />
    <Compile Include="Slices/User/Commands.fs" />
    <Compile Include="Slices/Review/Events.fs" />
    <Compile Include="Slices/Review/Commands.fs" />
    <Compile Include="Slices/DistributionPoint/Events.fs" />
    <Compile Include="Slices/DistributionPoint/Commands.fs" />
    <Compile Include="Slices/Tenant/Events.fs" />
    <Compile Include="Slices/Tenant/Commands.fs" />
    <Compile Include="Slices/Notification/Events.fs" />
    <Compile Include="Slices/Notification/Commands.fs" />

    <Compile Include="Slices/Common/SecretReader.fs" />
    <Compile Include="Slices/Common/Utils.fs" />
    <Compile Include="Slices/Common/CleanUpService.fs" />
    <Compile Include="Slices/Common/Security.fs" />
    <Compile Include="Slices/Details/Details.fs" />

    <Compile Include="Slices/Notification/MailBodyRetriever.fs" />
    <Compile Include="Slices/Notification/InAppMessagesRetriever.fs" />
    <Compile Include="Slices/User/UserMapping.fs" />
    <Compile Include="Slices/User/UserContextMapper.fs" />
    <Compile Include="Slices/Tenant/ServerCookieService.fs" />
    <Compile Include="Slices/Tenant/UserTenantResolverService.fs" />
    <Compile Include="Slices/Review/ReviewService.fs" />
    <Compile Include="Slices/User/UserService.fs" />
    <Compile Include="Slices/Reservation/ReservationService.fs" />
    <Compile Include="Slices/Author/AuthorService.fs" />
    <Compile Include="Slices/Loan/LoanService.fs" />
    <Compile Include="Slices/Book/VectorDbService.fs" />
    <Compile Include="Slices/Book/BookService.fs" />
    <Compile Include="Slices/Book/GeminiBasedBooksMetadataSearchService.fs" />
    <Compile Include="Slices/Book/GoogleBooksService.fs" />
    <Compile Include="Slices/Author/AuthorsSearchService.fs" />
    <Compile Include="Slices/Details/DetailsService.fs" />
    <Compile Include="Slices/DistributionPoint/DistributionPointService.fs" />
    <Compile Include="Slices/Book/TextEmbeddingService.fs" />
    <Compile Include="Slices/DataExport/DataExportService.fs" />
    <Compile Include="Slices/Admin/AdminService.fs" />
    <Compile Include="Slices/Tenant/TenantService.fs" />
    <Compile Include="Slices/Notification/MailQueue.fs" />
    <Compile Include="Slices/Notification/MailsQueueEvents.fs" />
    <Compile Include="Slices/Notification/MailsQueueCommands.fs" />
    <Compile Include="Slices/Notification/IMailResenderService.fs" />
    <Compile Include="Slices/Notification/MailResenderService.fs" />
    <Compile Include="Slices/Notification/MailResenderScheduler.fs" />
    <Compile Include="Slices/Reservation/ExpiredReservationsRemovalSchedule.fs" />
    <Compile Include="Slices/Author/RandomAuthorGeneratorService.fs" />
    <Compile Include="Slices/Book/RandomBooksGeneratorService.fs" />

    <Compile Include="Hubs/LibraryHub.fs" />

    <Compile Include="Slices/Notification/NotificationService.fs" />
    <Compile Include="Slices/Book/EmbeddingOrchestrationService.fs" />

    <Compile Include="Slices/Author/AuthorsSearchController.fs" />
    <Compile Include="Slices/Book/BooksController.fs" />
    <Compile Include="Slices/Loan/LoansController.fs" />
    <Compile Include="Slices/Author/AuthorsController.fs" />
    <Compile Include="Slices/DistributionPoint/DistributionPointsController.fs" />
    <Compile Include="Slices/Review/ReviewsController.fs" />
    <Compile Include="Slices/User/UsersController.fs" />
    <Compile Include="Slices/Reservation/ReservationsController.fs" />
    <Compile Include="Slices/Admin/AdminController.fs" />
    <Compile Include="Slices/Book/GoogleBooksController.fs" />
    <Compile Include="Slices/DataExport/DataExportController.fs" />
    <Compile Include="Slices/Details/DetailsController.fs" />
    <Compile Include="Slices/Book/VectorDbController.fs" />
    <Compile Include="Slices/AIAssistant/AIAssistantController.fs" />
    <Compile Include="Slices/Book/TextEmbeddingController.fs" />
    <Compile Include="Slices/Book/EmbeddingOrchestrationController.fs" />
    <Compile Include="Slices/Tenant/TenantController.fs" />
    <Compile Include="Slices/Notification/NotificationsController.fs" />
    <Compile Include="Slices/Notification/InAppMessagesRetrieverController.fs" />
    <Compile Include="Slices/Tenant/CookiesController.fs" />
    <Compile Include="Slices/Tenant/UserTenantResolverController.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.11.0" />
    <PackageReference Include="Bolero.Server" Version="0.*" />
    <PackageReference Include="Bolero.HotReload.Server" Version="0.*" />
    <PackageReference Include="Mailjet.Api" Version="4.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />

    <PackageReference Include="Sharpino" Version="6.0.4" />

  </ItemGroup>

</Project>
